name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Instalar librerías
        run: pip install -r nexo/requirements.txt
      - name: Revisar que el código no tenga errores de sintaxis
        run: python -m compileall app
      - name: Correr pruebas
        run: pytest || [ $? -eq 5 ]
